### ISSUE TITLE
". Zip" added to epub file

### ISSUE THREAD

**Issue by YanishW** [MakeYourLifeEasier/novel-ebook.com#20] opened 2019-12-28 13:43 UTC
Pretty much like the title said, when I downloaded the file it was an epub file, however it was named xxx.epub.zip. This caused some weird problems with my kobo, easily fixed now that I know about it but hey.. 😊

Ps. I don't remember exactly which novels had the error except for one : "i have a mansion in the post-apocalyptic world"

**Comment by MichaelGuardian** [comment] 2020-01-12 17:05
Hmm, never encountered this bug before. Do you remember which browser you used?

**Comment by YanishW** [comment] 2020-01-12 19:37
The first time I used kobos's beta browser but afterwards since the ereader
wasn't able to handle zip files I used my phone (android Chrome) sadly I
have no clue about which version it was at the time... I think it was
pre-android 10.

Ill see if I can replicate it Tuesday (out of the country atm).

Sidenote: I also noticed I got several results when searching "I have a
mansion..." all seemingly linking to the same novel. Perhaps the bug is
related to that?

**Comment by YanishW** [comment] 2020-01-12 19:42
Just tried replicating it and got the same result. (see screenshot). It's
Realy weird though as the file is an epub(and thus acts really weird when
you try and unzip it😅)

Not a huge problem and thanks again for the awesome site, it really helps
me a lot when I'm travelling on business and don't have access to my pc.

Kind regards,
Yanish

**Comment by MichaelGuardian** [comment] 2020-01-14 17:12
I don't see the screenshot, probably doesn't get added when you attach it via email.

I just tested it on my S9+ on Android 9 using Chrome and I couldn't replicate the bug. The mimetype and naming of the file seems to be fine.

The bug with the duplicated novels seems to be caused by the data source, nothing I can fix here until I find the time to launch v3 of the site. Will keep it in mind and reopen the issue when that happens.

Glad you like the site, it was one of the reasons I created it to begin with :)

**Comment by YanishW** [comment] 2020-01-14 17:22
Just tried it with my both my coworkers pixel (yesterday) and my old
oneplus 3. Pixel also had the same issue, old oneplus 3 got the epub
normally named... Very confusing (current phone is oneplus 6). Both Firefox
and desktop Firefox nightly worked fine.

Anyway, like I said, not a huge deal to me but I can see people stumbling
over it. Imo there's a fair chance of it being something to do with certain
Android Chrome version instead of your site.


Just so you know I'm not lying here's the screenshot again😜.
https://drive.google.com/file/d/0B0uFm9kenf3rZ05YcFNUWUYxY1ltQTJxdVlSMTRuaFAzd18w/view?usp=drivesdk

Thx for looking into it!

**Comment by MichaelGuardian** [comment] 2020-01-14 18:22
Ok I'll close the issue then. The zipping of the content is handled by third party code that was never intended to create epub files, so I can totally see how something like this might happen. 

It might be that there is no app associated with the .epub file extension. [This might solve the problem](https://www.trishtech.com/2014/02/set-file-associations-in-android-devices/)

**Closed by MichaelGuardian** 2020-01-14 18:22 UTC
